"""Visualize original ST anchors versus the complete 9957/g0 reconstruction.

The source H5AD contains both the original Xenium anchor cells and the cells
generated by reconstruction.  This utility deliberately does not use H&E,
domain, niche, or expression values: it only visualizes the final registered
XY coordinates (``spatial_st_corrected``) and physical Z (``z_um``).

For browser responsiveness the interactive/full static figures use a
deterministic point sample when the requested limit is smaller than the full
dataset.  The manifest records both the complete population and the rendered
population.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import anndata as ad
import matplotlib

matplotlib.use("Agg", force=True)
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import scipy.sparse

# Direct execution puts ``scripts/`` rather than the repository root on
# sys.path.  Add the root so the script works from the source checkout.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from deepspatial.vis_utils import (
    interactive_3d_labels,
    plot_3d_labels,
    plot_orthogonal_projections,
)


DEFAULT_H5AD = ROOT / (
    "data/9957_g0/"
    "reconstruction_final_thickness10_v4_manual_rotation/"
    "adata_9957_g0_full_thickness10_celltype_domain_niche.h5ad"
)
DEFAULT_OUTPUT = DEFAULT_H5AD.parent / "visualizations_st_vs_reconstruction"


def _palette(categories: list[str]) -> dict[str, str]:
    """Return an explicit, stable palette rather than library defaults."""

    colors = (
        list(px.colors.qualitative.Dark24)
        + list(px.colors.qualitative.Light24)
        + list(px.colors.qualitative.Set3)
    )
    return {category: colors[i % len(colors)] for i, category in enumerate(categories)}


def _ordered_sections(values: np.ndarray) -> list[str]:
    categories = sorted({str(value) for value in values}, key=lambda value: (int(value), value))
    return categories


def _light_adata(
    source: ad.AnnData,
    mask: np.ndarray,
    label_name: str,
    labels: np.ndarray,
) -> ad.AnnData:
    """Create an X-free AnnData view for plotting only.

    The reconstruction has 5,001 expression variables and can be very large.
    DeepSpatial's plotting functions only need ``obs`` and ``obsm``; this
    lightweight object avoids copying the expression matrix while preserving
    the exact selected coordinates and labels.
    """

    coordinates = np.asarray(source.obsm["spatial_st_corrected"])[mask]
    z_values = source.obs["z_um"].to_numpy()[mask]
    obs_names = source.obs_names.to_numpy()[mask]
    obs = pd.DataFrame(
        {
            label_name: labels.astype(str),
            "z_um": z_values,
        },
        index=obs_names,
    )
    return ad.AnnData(
        X=scipy.sparse.csr_matrix((len(obs), 1), dtype=np.float32),
        obs=obs,
        obsm={"spatial_st_corrected": coordinates},
    )


def _render_interactive(
    data: ad.AnnData,
    label_name: str,
    categories: list[str],
    output: Path,
    title: str,
    max_points: int,
) -> None:
    figure = interactive_3d_labels(
        data,
        color_col=label_name,
        palette=_palette(categories),
        spatial_key="spatial_st_corrected",
        z_key="z_um",
        point_size=1.35,
        opacity=0.72,
        bg_color="white",
        max_points=max_points,
        title=title,
        width=1500,
        height=950,
        save_html=None,
    )
    # Self-contained HTML is easier to move to another server or open offline.
    figure.write_html(output, include_plotlyjs=True, full_html=True)


def _render_static(
    data: ad.AnnData,
    label_name: str,
    categories: list[str],
    output: Path,
    stem: str,
    max_points: int,
    z_stretch: float,
) -> None:
    palette = _palette(categories)
    figure = plot_3d_labels(
        data,
        color_col=label_name,
        palette=palette,
        spatial_key="spatial_st_corrected",
        z_key="z_um",
        elev=25,
        azim=-58,
        z_stretch=z_stretch,
        point_size=0.34,
        alpha=0.62,
        max_points=max_points,
        bg_color="white",
        show=False,
    )
    figure.savefig(output / f"{stem}_3d_static.png", dpi=220, bbox_inches="tight")
    plt.close(figure)

    plot_orthogonal_projections(
        data,
        color_col=label_name,
        palette=palette,
        spatial_key="spatial_st_corrected",
        z_key="z_um",
        point_size=0.27,
        alpha=0.58,
        max_points=max_points,
        bg_color="white",
        save_png=str(output / f"{stem}_orthogonal_projections.png"),
        show=False,
    )
    plt.close("all")


def render(h5ad_path: Path, output: Path, max_points: int, static_z_stretch: float) -> dict:
    output.mkdir(parents=True, exist_ok=True)
    source = ad.read_h5ad(h5ad_path, backed="r")
    required_obs = {"z_um", "is_xenium_anchor"}
    required_obsm = {"spatial_st_corrected"}
    missing = sorted(
        [f"obs:{key}" for key in required_obs if key not in source.obs]
        + [f"obsm:{key}" for key in required_obsm if key not in source.obsm]
    )
    if missing:
        source.file.close()
        raise ValueError(f"Missing visualization fields: {missing}")

    anchor_mask = source.obs["is_xenium_anchor"].to_numpy(dtype=bool)
    anchor_sections = source.obs["section_id"].astype(str).to_numpy()[anchor_mask]
    section_categories = _ordered_sections(anchor_sections)
    anchor_data = _light_adata(
        source,
        anchor_mask,
        label_name="section_id",
        labels=anchor_sections,
    )

    # Remap the boolean source flag to readable labels without modifying the
    # source H5AD file.  ``anchor`` is the original ST population; ``virtual``
    # is generated by reconstruction.
    full_labels = np.where(anchor_mask, "anchor", "virtual")
    full_data = _light_adata(
        source,
        np.ones(source.n_obs, dtype=bool),
        label_name="reconstruction_status",
        labels=full_labels,
    )
    status_categories = ["anchor", "virtual"]

    outputs = {
        "st_anchor_interactive": output / "st_anchor_only_3d_interactive.html",
        "st_anchor_static": output / "st_anchor_only_3d_static.png",
        "st_anchor_orthogonal": output / "st_anchor_only_orthogonal_projections.png",
        "full_interactive": output / "full_reconstruction_3d_interactive.html",
        "full_static": output / "full_reconstruction_3d_static.png",
        "full_orthogonal": output / "full_reconstruction_orthogonal_projections.png",
    }

    _render_interactive(
        anchor_data,
        "section_id",
        section_categories,
        outputs["st_anchor_interactive"],
        "9957/g0 original ST anchors — registered 3D coordinates",
        max_points=max_points,
    )
    _render_static(
        anchor_data,
        "section_id",
        section_categories,
        output,
        "st_anchor_only",
        max_points=min(max_points, anchor_data.n_obs),
        z_stretch=static_z_stretch,
    )

    _render_interactive(
        full_data,
        "reconstruction_status",
        status_categories,
        outputs["full_interactive"],
        "9957/g0 complete 3D reconstruction — original ST anchors vs virtual cells",
        max_points=max_points,
    )
    _render_static(
        full_data,
        "reconstruction_status",
        status_categories,
        output,
        "full_reconstruction",
        max_points=min(max_points, full_data.n_obs),
        z_stretch=static_z_stretch,
    )

    manifest = {
        "source_h5ad": str(h5ad_path.resolve()),
        "source_shape": [int(source.n_obs), int(source.n_vars)],
        "spatial_key": "spatial_st_corrected",
        "z_key": "z_um",
        "anchor_count": int(anchor_mask.sum()),
        "virtual_count": int((~anchor_mask).sum()),
        "section_categories": section_categories,
        "full_status_categories": status_categories,
        "render_max_points": int(max_points),
        "sampling": "deterministic random sample from DeepSpatial vis_utils when population exceeds render_max_points",
        "static_z_stretch": float(static_z_stretch),
        "outputs": {key: str(path.resolve()) for key, path in outputs.items()},
    }
    (output / "st_vs_reconstruction_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n"
    )
    source.file.close()
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--h5ad", type=Path, default=DEFAULT_H5AD)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--max-points",
        type=int,
        default=250000,
        help="Maximum points per rendered figure; source data remain complete.",
    )
    parser.add_argument(
        "--static-z-stretch",
        type=float,
        default=4.0,
        help="Display-only Z stretch for static figures; interactive plots use physical aspect data.",
    )
    args = parser.parse_args()
    if args.max_points <= 0:
        raise ValueError("--max-points must be positive")
    manifest = render(
        args.h5ad.resolve(),
        args.output.resolve(),
        args.max_points,
        args.static_z_stretch,
    )
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
